# Netlify でビルドできなくなってしまったので GitHub Actions にやらせます

# 名前
name: Netlify Deploy

# 起動条件。main ブランチへ push もしくは手動起動
on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:

# やらせること
jobs:
  build:
    # OS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Node.js インストール
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
      
      # 依存関係
      - name: Package install
        run: npm i
      
      # 書き出し
      - name: Build page
        run: npm run deploy
        
      # Netlify アップロード
      - name: Upload page
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=./out --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
