# Netlify でビルドできなくなってしまったので GitHub Actions にやらせます

# 名前
name: Netlify Deploy

# 起動条件。main ブランチへ push もしくは手動起動
on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:

# やらせること
jobs:
  build:
    # OS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      # Node.js インストール
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.12.0
      
      # 依存関係
      - name: Package install
        run: npm i
      
      # 書き出し
      - name: Build page
        run: npm run deploy
        
      # Netlify アップロード
      # netlify/actions/cli@master が何年も放置されている、cli を直接呼び出したほうがよさそう
      # すでにビルド済みなので no-build
      - name: Upload page
        run: npm install -g netlify-cli && netlify deploy --no-build --dir="./out" --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
